Actor.create(:first_name=>"Actor1",:last_name=>"Actor 1 Surname")
Actor.create(:first_name=>"Actor2",:last_name=>"Actor 2 Surname")
Character.create(:name=>"Chatacter1")
Character.create(:name=>"Character2")
Show.create(:name=>"Show1")
Show.create(:name=>"Show2")